// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6rWepaLm-7iskjTdTOw3y5FF9-7w1q_Q',
    appId: '1:151306733573:web:0ddf8b52ad5103d06ff46c',
    messagingSenderId: '151306733573',
    projectId: 'uniplay-556bb',
    authDomain: 'uniplay-556bb.firebaseapp.com',
    databaseURL: 'https://uniplay-556bb-default-rtdb.firebaseio.com',
    storageBucket: 'uniplay-556bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY2eaA9tZGEZTePICYyI3YB0WDxSOc-Wk',
    appId: '1:151306733573:android:a392944d45f60cf16ff46c',
    messagingSenderId: '151306733573',
    projectId: 'uniplay-556bb',
    databaseURL: 'https://uniplay-556bb-default-rtdb.firebaseio.com',
    storageBucket: 'uniplay-556bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfnRgm3b2rlKSpqtgF1UFX-pLWZiFlLXY',
    appId: '1:151306733573:ios:a2a7c3a07ab06eb46ff46c',
    messagingSenderId: '151306733573',
    projectId: 'uniplay-556bb',
    databaseURL: 'https://uniplay-556bb-default-rtdb.firebaseio.com',
    storageBucket: 'uniplay-556bb.appspot.com',
    iosClientId: '151306733573-ma3ka8vveafq8fmdo99o6p461ra3aml5.apps.googleusercontent.com',
    iosBundleId: 'com.example.nuniplay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfnRgm3b2rlKSpqtgF1UFX-pLWZiFlLXY',
    appId: '1:151306733573:ios:dc36498af3f915126ff46c',
    messagingSenderId: '151306733573',
    projectId: 'uniplay-556bb',
    databaseURL: 'https://uniplay-556bb-default-rtdb.firebaseio.com',
    storageBucket: 'uniplay-556bb.appspot.com',
    iosClientId: '151306733573-vtasv92uh3hbfsvd5jbll4vg4a157na5.apps.googleusercontent.com',
    iosBundleId: 'com.example.nuniplay.RunnerTests',
  );
}
